// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search
{
    /// <summary>How much of each tool contract to return in `data.tools`. `compact` returns only `provider`, `capability`, and `description`. `summary` returns the full tool entry without `options` and `response`. `full` also returns `options`, `response`, and `examples`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchPostRequestBody_toolDetail
    {
        [EnumMember(Value = "compact")]
        #pragma warning disable CS1591
        Compact,
        #pragma warning restore CS1591
        [EnumMember(Value = "summary")]
        #pragma warning disable CS1591
        Summary,
        #pragma warning restore CS1591
        [EnumMember(Value = "full")]
        #pragma warning disable CS1591
        Full,
        #pragma warning restore CS1591
    }
}
