// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchPostRequestBody_sourcesMember4_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "alexandria")]
        #pragma warning disable CS1591
        Alexandria,
        #pragma warning restore CS1591
    }
}
