// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentTraceEventMember5 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identity of the agent that emitted the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceAgent? Agent { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceAgent Agent { get; set; }
#endif
        /// <summary>The durationMs property</summary>
        public int? DurationMs { get; set; }
        /// <summary>Null when outcome is succeeded; otherwise the structured error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceError? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceError Error { get; set; }
#endif
        /// <summary>Unique ID of this event.</summary>
        public Guid? EventId { get; set; }
        /// <summary>The occurredAt property</summary>
        public DateTimeOffset? OccurredAt { get; set; }
        /// <summary>The outcome property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_outcome? Outcome { get; set; }
        /// <summary>Monotonic sequence number from the emitting agent; order events by it.</summary>
        public int? ProducerSequence { get; set; }
        /// <summary>The agent job ID this event belongs to.</summary>
        public Guid? RunId { get; set; }
        /// <summary>The schemaVersion property</summary>
        public int? SchemaVersion { get; set; }
        /// <summary>Emitted when an agent finishes.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5"/> and sets the default values.
        /// </summary>
        public AgentTraceEventMember5()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "agent", n => { Agent = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceAgent>(global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceAgent.CreateFromDiscriminatorValue); } },
                { "durationMs", n => { DurationMs = n.GetIntValue(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceError>(global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceError.CreateFromDiscriminatorValue); } },
                { "eventId", n => { EventId = n.GetGuidValue(); } },
                { "occurredAt", n => { OccurredAt = n.GetDateTimeOffsetValue(); } },
                { "outcome", n => { Outcome = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_outcome>(); } },
                { "producerSequence", n => { ProducerSequence = n.GetIntValue(); } },
                { "runId", n => { RunId = n.GetGuidValue(); } },
                { "schemaVersion", n => { SchemaVersion = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceAgent>("agent", Agent);
            writer.WriteIntValue("durationMs", DurationMs);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceError>("error", Error);
            writer.WriteGuidValue("eventId", EventId);
            writer.WriteDateTimeOffsetValue("occurredAt", OccurredAt);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_outcome>("outcome", Outcome);
            writer.WriteIntValue("producerSequence", ProducerSequence);
            writer.WriteGuidValue("runId", RunId);
            writer.WriteIntValue("schemaVersion", SchemaVersion);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentTraceEventMember5_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
