// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AgentTraceError_source
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "tool")]
        #pragma warning disable CS1591
        Tool,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing")]
        #pragma warning disable CS1591
        Billing,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
    }
}
