// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Emitted when a non-fatal error occurs during the run.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember13_type
    {
        [EnumMember(Value = "error.occurred")]
        #pragma warning disable CS1591
        ErrorOccurred,
        #pragma warning restore CS1591
    }
}
