// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Terminal event for the run.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember3_type
    {
        [EnumMember(Value = "run.finished")]
        #pragma warning disable CS1591
        RunFinished,
        #pragma warning restore CS1591
    }
}
