// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Emitted when the orchestrator reports progress.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember8_type
    {
        [EnumMember(Value = "progress.reported")]
        #pragma warning disable CS1591
        ProgressReported,
        #pragma warning restore CS1591
    }
}
