// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Emitted when a tool call finishes.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember11_type
    {
        [EnumMember(Value = "tool_call.finished")]
        #pragma warning disable CS1591
        Tool_callFinished,
        #pragma warning restore CS1591
    }
}
