// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AgentTraceAgent_role
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "orchestrator")]
        #pragma warning disable CS1591
        Orchestrator,
        #pragma warning restore CS1591
        [EnumMember(Value = "subagent")]
        #pragma warning disable CS1591
        Subagent,
        #pragma warning restore CS1591
        [EnumMember(Value = "system")]
        #pragma warning disable CS1591
        System,
        #pragma warning restore CS1591
    }
}
