// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AgentExchangeSummary_onTermsRequired
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "skip")]
        #pragma warning disable CS1591
        Skip,
        #pragma warning restore CS1591
        [EnumMember(Value = "ask")]
        #pragma warning disable CS1591
        Ask,
        #pragma warning restore CS1591
    }
}
