// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>`calls`: paid provider calls held back by `requireApproval`. `terms`: providers whose data terms need accepting (`onTermsRequired: &quot;ask&quot;`). Absent on items written before terms offers existed, which are `calls`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentPendingApproval_kind
    {
        [EnumMember(Value = "calls")]
        #pragma warning disable CS1591
        Calls,
        #pragma warning restore CS1591
        [EnumMember(Value = "terms")]
        #pragma warning disable CS1591
        Terms,
        #pragma warning restore CS1591
    }
}
