// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Emitted when an output artifact changes.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember12_type
    {
        [EnumMember(Value = "artifact.updated")]
        #pragma warning disable CS1591
        ArtifactUpdated,
        #pragma warning restore CS1591
    }
}
