// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AgentTraceArtifact_change
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "init")]
        #pragma warning disable CS1591
        Init,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "append")]
        #pragma warning disable CS1591
        Append,
        #pragma warning restore CS1591
        [EnumMember(Value = "modify")]
        #pragma warning disable CS1591
        Modify,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
    }
}
