// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Emitted when a browser session starts.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentTraceEventMember6_type
    {
        [EnumMember(Value = "browser.session.started")]
        #pragma warning disable CS1591
        BrowserSessionStarted,
        #pragma warning restore CS1591
    }
}
