// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// What the turn stopped to ask. Answer it on the next turn of the thread with `exchange.approve` or `exchange.decline`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentPendingApproval : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The paid calls waiting for approval. Empty on a `terms` approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_calls>? Calls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_calls> Calls { get; set; }
#endif
        /// <summary>Send this as `approvalId`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>`calls`: paid provider calls held back by `requireApproval`. `terms`: providers whose data terms need accepting (`onTermsRequired: &quot;ask&quot;`). Absent on items written before terms offers existed, which are `calls`.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_kind? Kind { get; set; }
        /// <summary>Why the agent wants to make these calls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Null until a later turn answers the approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_resolution? Resolution { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_resolution Resolution { get; set; }
#endif
        /// <summary>On a `terms` approval, the providers whose terms need accepting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_terms>? Terms { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_terms> Terms { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval"/> and sets the default values.
        /// </summary>
        public AgentPendingApproval()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calls", n => { Calls = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_calls>(global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_calls.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_kind>(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "resolution", n => { Resolution = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_resolution>(global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_resolution.CreateFromDiscriminatorValue); } },
                { "terms", n => { Terms = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_terms>(global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_terms.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_calls>("calls", Calls);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_kind>("kind", Kind);
            writer.WriteStringValue("reason", Reason);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_resolution>("resolution", Resolution);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.AgentPendingApproval_terms>("terms", Terms);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
