// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AlexandriaCall_options_expand
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "options")]
        #pragma warning disable CS1591
        Options,
        #pragma warning restore CS1591
        [EnumMember(Value = "response")]
        #pragma warning disable CS1591
        Response,
        #pragma warning restore CS1591
        [EnumMember(Value = "examples")]
        #pragma warning disable CS1591
        Examples,
        #pragma warning restore CS1591
    }
}
