// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchScrapeStatusResponseObj_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>HTML version of the content on page if `includeHtml`  is true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Html { get; set; }
#nullable restore
#else
        public string Html { get; set; }
#endif
        /// <summary>List of links on the page if `includeLinks` is true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Links { get; set; }
#nullable restore
#else
        public List<string> Links { get; set; }
#endif
        /// <summary>The markdown property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Markdown { get; set; }
#nullable restore
#else
        public string Markdown { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_metadata Metadata { get; set; }
#endif
        /// <summary>Raw HTML content of the page if `includeRawHtml`  is true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawHtml { get; set; }
#nullable restore
#else
        public string RawHtml { get; set; }
#endif
        /// <summary>Screenshot of the page if `includeScreenshot` is true</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Screenshot { get; set; }
#nullable restore
#else
        public string Screenshot { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data"/> and sets the default values.
        /// </summary>
        public BatchScrapeStatusResponseObj_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "html", n => { Html = n.GetStringValue(); } },
                { "links", n => { Links = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "markdown", n => { Markdown = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_metadata>(global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_metadata.CreateFromDiscriminatorValue); } },
                { "rawHtml", n => { RawHtml = n.GetStringValue(); } },
                { "screenshot", n => { Screenshot = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("html", Html);
            writer.WriteCollectionOfPrimitiveValues<string>("links", Links);
            writer.WriteStringValue("markdown", Markdown);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_metadata>("metadata", Metadata);
            writer.WriteStringValue("rawHtml", RawHtml);
            writer.WriteStringValue("screenshot", Screenshot);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
