// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BatchScrapeStatusResponseObj_data_blocks_items : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>[x0, y0, x1, y1] normalized 0-1 relative to the page width/height. Multiply by the page width/height to get pixel coordinates. Null when the page has no known dimensions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? Bbox { get; set; }
#nullable restore
#else
        public List<double?> Bbox { get; set; }
#endif
        /// <summary>The confidence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items_confidence? Confidence { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items_confidence Confidence { get; set; }
#endif
        /// <summary>Markdown fragment this block contributed to the document markdown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>Stable within a response: p&lt;page&gt;.b&lt;index in reading order&gt;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Raw layout-model label, passthrough for forward compatibility.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>[start, end) character offsets into the document markdown covering this block&apos;s fragment. Null when a post-processing transform rewrote the fragment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? MarkdownSpan { get; set; }
#nullable restore
#else
        public List<int?> MarkdownSpan { get; set; }
#endif
        /// <summary>The readingOrder property</summary>
        public int? ReadingOrder { get; set; }
        /// <summary>Pipeline path that produced the block (for example native_text, layout_ocr, tsr, formula_model, full_page).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>Block type: title, section_header, text, table, formula, figure, caption, page_number, page_header, page_footer. New types may appear over time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items"/> and sets the default values.
        /// </summary>
        public BatchScrapeStatusResponseObj_data_blocks_items()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bbox", n => { Bbox = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "confidence", n => { Confidence = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items_confidence>(global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items_confidence.CreateFromDiscriminatorValue); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "markdownSpan", n => { MarkdownSpan = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "readingOrder", n => { ReadingOrder = n.GetIntValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<double?>("bbox", Bbox);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.BatchScrapeStatusResponseObj_data_blocks_items_confidence>("confidence", Confidence);
            writer.WriteStringValue("content", Content);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("label", Label);
            writer.WriteCollectionOfPrimitiveValues<int?>("markdownSpan", MarkdownSpan);
            writer.WriteIntValue("readingOrder", ReadingOrder);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
