// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CrawlErrorsResponseObj : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Errored scrape jobs and error details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj_errors>? Errors { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj_errors> Errors { get; set; }
#endif
        /// <summary>List of URLs that were attempted in scraping but were blocked by robots.txt</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RobotsBlocked { get; set; }
#nullable restore
#else
        public List<string> RobotsBlocked { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj"/> and sets the default values.
        /// </summary>
        public CrawlErrorsResponseObj()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj_errors>(global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj_errors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "robotsBlocked", n => { RobotsBlocked = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.CrawlErrorsResponseObj_errors>("errors", Errors);
            writer.WriteCollectionOfPrimitiveValues<string>("robotsBlocked", RobotsBlocked);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
