// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CrawlMember14_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "highlights")]
        #pragma warning disable CS1591
        Highlights,
        #pragma warning restore CS1591
    }
}
