// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeveloperSearchResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Outcome for each result type. Check this when an expected result type is missing: `skipped` means your `types` value did not ask for that type, while `degraded` or `unavailable` means the gap came from the index or from a filter, not from the query. A repository filter is one such cause — see [how the repository filters scope a search](/api-reference/endpoint/developer-search#how-the-repository-filters-scope-a-search).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_coverage? Coverage { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_coverage Coverage { get; set; }
#endif
        /// <summary>Present only when `repos` was sent. Echoes each slug with whether it is indexed, plus a per-type breakdown under `types`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos>? Repos { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos> Repos { get; set; }
#endif
        /// <summary>Whether the ranked list went through the reranking stage.</summary>
        public bool? Reranked { get; set; }
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResult>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResult> Results { get; set; }
#endif
        /// <summary>Present only when `sources` was sent. Reports each id exactly as requested along with whether it is indexed. `indexed: true` means the source has a published generation, so documentation evidence from it may appear; `indexed: false` means nothing from that id can match, which distinguishes an id that is not in the index from a query that simply found nothing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_sources>? Sources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_sources> Sources { get; set; }
#endif
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse"/> and sets the default values.
        /// </summary>
        public DeveloperSearchResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coverage", n => { Coverage = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_coverage>(global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_coverage.CreateFromDiscriminatorValue); } },
                { "repos", n => { Repos = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos>(global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reranked", n => { Reranked = n.GetBoolValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResult>(global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_sources>(global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_sources.CreateFromDiscriminatorValue)?.AsList(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_coverage>("coverage", Coverage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos>("repos", Repos);
            writer.WriteBoolValue("reranked", Reranked);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResult>("results", Results);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_sources>("sources", Sources);
            writer.WriteBoolValue("success", Success);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
