// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DeveloperSearchResponse_coverage_pull_request
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ok")]
        #pragma warning disable CS1591
        Ok,
        #pragma warning restore CS1591
        [EnumMember(Value = "degraded")]
        #pragma warning disable CS1591
        Degraded,
        #pragma warning restore CS1591
        [EnumMember(Value = "unavailable")]
        #pragma warning disable CS1591
        Unavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "skipped")]
        #pragma warning disable CS1591
        Skipped,
        #pragma warning restore CS1591
    }
}
