// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Which result types are indexed for this repository: `issue`, `pullRequest`, and `readme`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeveloperSearchResponse_repos_types : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The issue property</summary>
        public bool? Issue { get; set; }
        /// <summary>The pullRequest property</summary>
        public bool? PullRequest { get; set; }
        /// <summary>The readme property</summary>
        public bool? Readme { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos_types"/> and sets the default values.
        /// </summary>
        public DeveloperSearchResponse_repos_types()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos_types"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos_types CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse_repos_types();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "issue", n => { Issue = n.GetBoolValue(); } },
                { "pullRequest", n => { PullRequest = n.GetBoolValue(); } },
                { "readme", n => { Readme = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("issue", Issue);
            writer.WriteBoolValue("pullRequest", PullRequest);
            writer.WriteBoolValue("readme", Readme);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
