// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// A catalogued provider tool discovered via Alexandria, semantic search, or domain matching.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DiscoveredTool : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The provider-relative capability.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Capability { get; set; }
#nullable restore
#else
        public string Capability { get; set; }
#endif
        /// <summary>Credits charged per execution of this tool.</summary>
        public int? CreditsCost { get; set; }
        /// <summary>Human-readable description of what the tool does.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The tool&apos;s identifier, formatted as `provider/capability`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Why this tool was surfaced.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_matchedBy?>? MatchedBy { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_matchedBy?> MatchedBy { get; set; }
#endif
        /// <summary>URLs whose domain matched this tool, when matched by domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MatchedUrls { get; set; }
#nullable restore
#else
        public List<string> MatchedUrls { get; set; }
#endif
        /// <summary>Human-readable name of the tool.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The capability&apos;s accepted options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_options>? Options { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_options> Options { get; set; }
#endif
        /// <summary>Whether `creditsCost` is charged per record returned rather than per call.</summary>
        public bool? PerRecord { get; set; }
        /// <summary>The catalogued provider.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provider { get; set; }
#nullable restore
#else
        public string Provider { get; set; }
#endif
        /// <summary>Description of the shape of a successful response&apos;s `data`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_response? Response { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_response Response { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool"/> and sets the default values.
        /// </summary>
        public DiscoveredTool()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capability", n => { Capability = n.GetStringValue(); } },
                { "creditsCost", n => { CreditsCost = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "matchedBy", n => { MatchedBy = n.GetCollectionOfEnumValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_matchedBy>()?.AsList(); } },
                { "matchedUrls", n => { MatchedUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "options", n => { Options = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_options>(global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_options.CreateFromDiscriminatorValue)?.AsList(); } },
                { "perRecord", n => { PerRecord = n.GetBoolValue(); } },
                { "provider", n => { Provider = n.GetStringValue(); } },
                { "response", n => { Response = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_response>(global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_response.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("capability", Capability);
            writer.WriteIntValue("creditsCost", CreditsCost);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_matchedBy>("matchedBy", MatchedBy);
            writer.WriteCollectionOfPrimitiveValues<string>("matchedUrls", MatchedUrls);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_options>("options", Options);
            writer.WriteBoolValue("perRecord", PerRecord);
            writer.WriteStringValue("provider", Provider);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.DiscoveredTool_response>("response", Response);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
