// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Submit feedback for a v2 job. Include at least one substantive signal such as issues, note, valuableSources, missingContent, querySuggestions, url, or pageNumbers.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EndpointFeedbackRequest : global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackRequest, IParsable
    {
        /// <summary>The endpoint property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_endpoint? Endpoint { get; set; }
        /// <summary>The issues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Issues { get; set; }
#nullable restore
#else
        public List<string> Issues { get; set; }
#endif
        /// <summary>The jobId property</summary>
        public Guid? JobId { get; set; }
        /// <summary>Small endpoint-specific metadata object. Must be 8KB or smaller; do not include full endpoint results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_metadata Metadata { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The pageNumbers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? PageNumbers { get; set; }
#nullable restore
#else
        public List<int?> PageNumbers { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "endpoint", n => { Endpoint = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_endpoint>(); } },
                { "issues", n => { Issues = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "jobId", n => { JobId = n.GetGuidValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_metadata>(global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_metadata.CreateFromDiscriminatorValue); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "pageNumbers", n => { PageNumbers = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_endpoint>("endpoint", Endpoint);
            writer.WriteCollectionOfPrimitiveValues<string>("issues", Issues);
            writer.WriteGuidValue("jobId", JobId);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.EndpointFeedbackRequest_metadata>("metadata", Metadata);
            writer.WriteStringValue("note", Note);
            writer.WriteCollectionOfPrimitiveValues<int?>("pageNumbers", PageNumbers);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("url", Url);
        }
    }
}
#pragma warning restore CS0618
