// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExtractMember6_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "images")]
        #pragma warning disable CS1591
        Images,
        #pragma warning restore CS1591
    }
}
