// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExtractMember10_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "branding")]
        #pragma warning disable CS1591
        Branding,
        #pragma warning restore CS1591
    }
}
