// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FeedbackResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alreadySubmitted property</summary>
        public bool? AlreadySubmitted { get; set; }
        /// <summary>The creditsRefunded property</summary>
        public double? CreditsRefunded { get; set; }
        /// <summary>The creditsRefundedToday property</summary>
        public double? CreditsRefundedToday { get; set; }
        /// <summary>The dailyCapReached property</summary>
        public bool? DailyCapReached { get; set; }
        /// <summary>The dailyRefundCap property</summary>
        public double? DailyRefundCap { get; set; }
        /// <summary>The feedbackId property</summary>
        public Guid? FeedbackId { get; set; }
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>The warning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Warning { get; set; }
#nullable restore
#else
        public string Warning { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.FeedbackResponse"/> and sets the default values.
        /// </summary>
        public FeedbackResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.FeedbackResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.FeedbackResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.FeedbackResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alreadySubmitted", n => { AlreadySubmitted = n.GetBoolValue(); } },
                { "creditsRefunded", n => { CreditsRefunded = n.GetDoubleValue(); } },
                { "creditsRefundedToday", n => { CreditsRefundedToday = n.GetDoubleValue(); } },
                { "dailyCapReached", n => { DailyCapReached = n.GetBoolValue(); } },
                { "dailyRefundCap", n => { DailyRefundCap = n.GetDoubleValue(); } },
                { "feedbackId", n => { FeedbackId = n.GetGuidValue(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
                { "warning", n => { Warning = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("alreadySubmitted", AlreadySubmitted);
            writer.WriteDoubleValue("creditsRefunded", CreditsRefunded);
            writer.WriteDoubleValue("creditsRefundedToday", CreditsRefundedToday);
            writer.WriteBoolValue("dailyCapReached", DailyCapReached);
            writer.WriteDoubleValue("dailyRefundCap", DailyRefundCap);
            writer.WriteGuidValue("feedbackId", FeedbackId);
            writer.WriteBoolValue("success", Success);
            writer.WriteStringValue("warning", Warning);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
