// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>The catalogue level of the items on this page.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FindToolsData_level
    {
        [EnumMember(Value = "providers")]
        #pragma warning disable CS1591
        Providers,
        #pragma warning restore CS1591
        [EnumMember(Value = "groups")]
        #pragma warning disable CS1591
        Groups,
        #pragma warning restore CS1591
        [EnumMember(Value = "tools")]
        #pragma warning disable CS1591
        Tools,
        #pragma warning restore CS1591
    }
}
