// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Partial monitor update payload. Include at least one field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MonitorUpdateRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Plain-language goal used to judge whether changed pages are meaningful. If provided and `judgeEnabled` is omitted, judging is enabled automatically.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Goal { get; set; }
#nullable restore
#else
        public string Goal { get; set; }
#endif
        /// <summary>Whether to judge changed pages against `goal`. Requires a non-empty `goal` to run.</summary>
        public bool? JudgeEnabled { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The notification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorNotification? Notification { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorNotification Notification { get; set; }
#endif
        /// <summary>The retentionDays property</summary>
        public int? RetentionDays { get; set; }
        /// <summary>Schedule for monitor checks. Provide either `cron` or `text`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorSchedule? Schedule { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorSchedule Schedule { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest_status? Status { get; set; }
        /// <summary>The targets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorTarget>? Targets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorTarget> Targets { get; set; }
#endif
        /// <summary>Webhook destination for monitor page and check completion events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorWebhook? Webhook { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorWebhook Webhook { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest"/> and sets the default values.
        /// </summary>
        public MonitorUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "goal", n => { Goal = n.GetStringValue(); } },
                { "judgeEnabled", n => { JudgeEnabled = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notification", n => { Notification = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorNotification>(global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorNotification.CreateFromDiscriminatorValue); } },
                { "retentionDays", n => { RetentionDays = n.GetIntValue(); } },
                { "schedule", n => { Schedule = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorSchedule>(global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorSchedule.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest_status>(); } },
                { "targets", n => { Targets = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorTarget>(global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorTarget.CreateFromDiscriminatorValue)?.AsList(); } },
                { "webhook", n => { Webhook = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorWebhook>(global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorWebhook.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("goal", Goal);
            writer.WriteBoolValue("judgeEnabled", JudgeEnabled);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorNotification>("notification", Notification);
            writer.WriteIntValue("retentionDays", RetentionDays);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorSchedule>("schedule", Schedule);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorUpdateRequest_status>("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorTarget>("targets", Targets);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorWebhook>("webhook", Webhook);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
