// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MonitorTargetMember1_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "scrape")]
        #pragma warning disable CS1591
        Scrape,
        #pragma warning restore CS1591
    }
}
