// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MonitorWebhook_events
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "monitor.page")]
        #pragma warning disable CS1591
        MonitorPage,
        #pragma warning restore CS1591
        [EnumMember(Value = "monitor.check.completed")]
        #pragma warning disable CS1591
        MonitorCheckCompleted,
        #pragma warning restore CS1591
    }
}
