// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Optional parse options sent as JSON in the multipart `options` field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParseOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enable ad and cookie popup blocking.</summary>
        public bool? BlockAds { get; set; }
        /// <summary>Tags to exclude from the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeTags { get; set; }
#nullable restore
#else
        public List<string> ExcludeTags { get; set; }
#endif
        /// <summary>Output formats supported for `/parse` uploads. Browser-rendering formats and change tracking are not supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse>? Formats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse> Formats { get; set; }
#endif
        /// <summary>Headers to send when additional network requests are required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_headers Headers { get; set; }
#endif
        /// <summary>Tags to include in the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludeTags { get; set; }
#nullable restore
#else
        public List<string> IncludeTags { get; set; }
#endif
        /// <summary>Optional integration identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Integration { get; set; }
#nullable restore
#else
        public string Integration { get; set; }
#endif
        /// <summary>Only return the main content of the page excluding headers, navs, footers, etc.</summary>
        public bool? OnlyMainContent { get; set; }
        /// <summary>Origin identifier for analytics and logging.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Origin { get; set; }
#nullable restore
#else
        public string Origin { get; set; }
#endif
        /// <summary>Controls file parser behavior when relevant (for example PDF parser mode).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_parsers>? Parsers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_parsers> Parsers { get; set; }
#endif
        /// <summary>Proxy mode for parse uploads. `/parse` supports only `basic` and `auto`.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_proxy? Proxy { get; set; }
        /// <summary>Remove base64-encoded images from output and keep alt text placeholders.</summary>
        public bool? RemoveBase64Images { get; set; }
        /// <summary>Skip TLS certificate verification when making requests.</summary>
        public bool? SkipTlsVerification { get; set; }
        /// <summary>Timeout in milliseconds for the request. Default is 30000 (30 seconds). Maximum is 300000 (300 seconds).</summary>
        public int? Timeout { get; set; }
        /// <summary>If true, this will enable zero data retention for this parse. To enable this feature, please contact help@firecrawl.dev</summary>
        public bool? ZeroDataRetention { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions"/> and sets the default values.
        /// </summary>
        public ParseOptions()
        {
            AdditionalData = new Dictionary<string, object>();
            Origin = "api";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockAds", n => { BlockAds = n.GetBoolValue(); } },
                { "excludeTags", n => { ExcludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "formats", n => { Formats = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse>(global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_headers>(global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_headers.CreateFromDiscriminatorValue); } },
                { "includeTags", n => { IncludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "integration", n => { Integration = n.GetStringValue(); } },
                { "onlyMainContent", n => { OnlyMainContent = n.GetBoolValue(); } },
                { "origin", n => { Origin = n.GetStringValue(); } },
                { "parsers", n => { Parsers = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_parsers>(global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_parsers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "proxy", n => { Proxy = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_proxy>(); } },
                { "removeBase64Images", n => { RemoveBase64Images = n.GetBoolValue(); } },
                { "skipTlsVerification", n => { SkipTlsVerification = n.GetBoolValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "zeroDataRetention", n => { ZeroDataRetention = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("blockAds", BlockAds);
            writer.WriteCollectionOfPrimitiveValues<string>("excludeTags", ExcludeTags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse>("formats", Formats);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_headers>("headers", Headers);
            writer.WriteCollectionOfPrimitiveValues<string>("includeTags", IncludeTags);
            writer.WriteStringValue("integration", Integration);
            writer.WriteBoolValue("onlyMainContent", OnlyMainContent);
            writer.WriteStringValue("origin", Origin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_parsers>("parsers", Parsers);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions_proxy>("proxy", Proxy);
            writer.WriteBoolValue("removeBase64Images", RemoveBase64Images);
            writer.WriteBoolValue("skipTlsVerification", SkipTlsVerification);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteBoolValue("zeroDataRetention", ZeroDataRetention);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Parse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1? ParseMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1 ParseMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2? ParseMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2 ParseMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3? ParseMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3 ParseMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4? ParseMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4 ParseMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5? ParseMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5 ParseMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6? ParseMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6 ParseMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7? ParseMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7 ParseMember7 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseOptions.Parse();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember1 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember2 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember3 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember4 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember5 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember6 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ParseMember7 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ParseMember1 != null)
                {
                    return ParseMember1.GetFieldDeserializers();
                }
                else if(ParseMember2 != null)
                {
                    return ParseMember2.GetFieldDeserializers();
                }
                else if(ParseMember3 != null)
                {
                    return ParseMember3.GetFieldDeserializers();
                }
                else if(ParseMember4 != null)
                {
                    return ParseMember4.GetFieldDeserializers();
                }
                else if(ParseMember5 != null)
                {
                    return ParseMember5.GetFieldDeserializers();
                }
                else if(ParseMember6 != null)
                {
                    return ParseMember6.GetFieldDeserializers();
                }
                else if(ParseMember7 != null)
                {
                    return ParseMember7.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ParseMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember1>(null, ParseMember1);
                }
                else if(ParseMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember2>(null, ParseMember2);
                }
                else if(ParseMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember3>(null, ParseMember3);
                }
                else if(ParseMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember4>(null, ParseMember4);
                }
                else if(ParseMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember5>(null, ParseMember5);
                }
                else if(ParseMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember6>(null, ParseMember6);
                }
                else if(ParseMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ParseMember7>(null, ParseMember7);
                }
            }
        }
    }
}
#pragma warning restore CS0618
