// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>Public PII entity buckets supported by Firecrawl redaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RedactPIIEntity
    {
        [EnumMember(Value = "PERSON")]
        #pragma warning disable CS1591
        PERSON,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        EMAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHONE")]
        #pragma warning disable CS1591
        PHONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCATION")]
        #pragma warning disable CS1591
        LOCATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "FINANCIAL")]
        #pragma warning disable CS1591
        FINANCIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECRET")]
        #pragma warning disable CS1591
        SECRET,
        #pragma warning restore CS1591
    }
}
