// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>`tag` replaces spans with placeholders like `&lt;EMAIL&gt;`, `mask` replaces characters with `*`, and `remove` deletes the span text.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RedactPIIOptions_replaceStyle
    {
        [EnumMember(Value = "tag")]
        #pragma warning disable CS1591
        Tag,
        #pragma warning restore CS1591
        [EnumMember(Value = "mask")]
        #pragma warning disable CS1591
        Mask,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
    }
}
