// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResearchPaperResult : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abstract property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Abstract { get; set; }
#nullable restore
#else
        public string Abstract { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Source identifiers grouped by namespace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchIdMap? Ids { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchIdMap Ids { get; set; }
#endif
        /// <summary>Canonical paper id, or web:&lt;url&gt; for SERP-discovered display results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaperId { get; set; }
#nullable restore
#else
        public string PaperId { get; set; }
#endif
        /// <summary>Preferred cite/fetch id such as arxiv:&lt;id&gt;, pmid:&lt;id&gt;, pmcid:&lt;id&gt;, or doi:&lt;id&gt;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryId { get; set; }
#nullable restore
#else
        public string PrimaryId { get; set; }
#endif
        /// <summary>The score property</summary>
        public double? Score { get; set; }
        /// <summary>The signals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperSignals? Signals { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperSignals Signals { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperResult"/> and sets the default values.
        /// </summary>
        public ResearchPaperResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abstract", n => { Abstract = n.GetStringValue(); } },
                { "ids", n => { Ids = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchIdMap>(global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchIdMap.CreateFromDiscriminatorValue); } },
                { "paperId", n => { PaperId = n.GetStringValue(); } },
                { "primaryId", n => { PrimaryId = n.GetStringValue(); } },
                { "score", n => { Score = n.GetDoubleValue(); } },
                { "signals", n => { Signals = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperSignals>(global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperSignals.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("abstract", Abstract);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchIdMap>("ids", Ids);
            writer.WriteStringValue("paperId", PaperId);
            writer.WriteStringValue("primaryId", PrimaryId);
            writer.WriteDoubleValue("score", Score);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ResearchPaperSignals>("signals", Signals);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
