// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScrapeOptions : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Actions to perform on the page before grabbing the content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Actions { get; set; }
#nullable restore
#else
        public UntypedNode Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enables ad-blocking and cookie popup blocking.</summary>
        public bool? BlockAds { get; set; }
        /// <summary>Tags to exclude from the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeTags { get; set; }
#nullable restore
#else
        public List<string> ExcludeTags { get; set; }
#endif
        /// <summary>Output formats to include in the response. You can specify one or more formats, either as strings (e.g., `&apos;markdown&apos;`) or as objects with additional options (e.g., `{ type: &apos;json&apos;, schema: {...} }`). Some formats require specific options to be set. Example: `[&apos;markdown&apos;, { type: &apos;json&apos;, schema: {...} }]`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor>? Formats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor> Formats { get; set; }
#endif
        /// <summary>Headers to send with the request. Can be used to send cookies, user-agent, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_headers Headers { get; set; }
#endif
        /// <summary>Tags to include in the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludeTags { get; set; }
#nullable restore
#else
        public List<string> IncludeTags { get; set; }
#endif
        /// <summary>Location settings for the request. When specified, this will use an appropriate proxy if available and emulate the corresponding language and timezone settings. Defaults to &apos;US&apos; if not specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_location? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_location Location { get; set; }
#endif
        /// <summary>If true, serves the request from Firecrawl&apos;s cache only and never makes an outbound request to the target URL. Designed for compliance-constrained or air-gapped environments where the scrape request itself could leak sensitive information. On cache miss, returns a 404 with error code SCRAPE_LOCKDOWN_CACHE_MISS (the URL is never logged on miss). Lockdown requests are treated as zero data retention. Default maxAge is extended to 2 years so existing cached pages remain eligible. Billed at 5 credits on hit, 1 credit on cache miss.</summary>
        public bool? Lockdown { get; set; }
        /// <summary>Returns a cached version of the page if it is younger than this age in milliseconds. If a cached version of the page is older than this value, the page will be scraped. If you do not need extremely fresh data, enabling this can speed up your scrapes by 500%. Defaults to 2 days.</summary>
        public int? MaxAge { get; set; }
        /// <summary>When set, the request only checks the cache and never triggers a fresh scrape. The value is in milliseconds and specifies the minimum age the cached data must be. If matching cached data exists, it is returned instantly. If no cached data is found, a 404 with error code SCRAPE_NO_CACHED_DATA is returned. Set to 1 to accept any cached data regardless of age.</summary>
        public int? MinAge { get; set; }
        /// <summary>Set to true if you want to emulate scraping from a mobile device. Useful for testing responsive pages and taking mobile screenshots.</summary>
        public bool? Mobile { get; set; }
        /// <summary>Beta. Run an additional LLM-based pass over the generated markdown to remove residual boilerplate that `onlyMainContent` can miss (cookie banners, ad blocks, social share widgets, breadcrumbs, newsletter signups, comment sections, related-article lists). Headings, lists, tables, code blocks, image references, and inline links are preserved. Can be combined with `onlyMainContent` (the most common setup) or used on its own. Skipped with a warning when the markdown exceeds the cleaning model&apos;s output token limit (the original markdown is preserved). Not supported on zero-data-retention requests.</summary>
        public bool? OnlyCleanContent { get; set; }
        /// <summary>Only return the main content of the page excluding headers, navs, footers, etc. This is a deterministic HTML-level filter applied before markdown is generated; no LLM is involved.</summary>
        public bool? OnlyMainContent { get; set; }
        /// <summary>Controls how files are processed during scraping. When &quot;pdf&quot; is included (default), the PDF content is extracted and converted to markdown format, with billing based on the number of pages (1 credit per page). When an empty array is passed, the PDF file is returned in base64 encoding with a flat rate of 1 credit for the entire PDF.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_parsers>? Parsers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_parsers> Parsers { get; set; }
#endif
        /// <summary>Enable persistent browser storage across scrape and interact sessions. Pass a profile when scraping to preserve cookies, localStorage, and session data. Sessions with the same profile name share browser state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_profile? Profile { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_profile Profile { get; set; }
#endif
        /// <summary>Specifies the type of proxy to use. - **basic**: Proxies for scraping sites with none to basic anti-bot solutions. Fast and usually works. - **enhanced**: Enhanced proxies for scraping sites with advanced anti-bot solutions. Slower, but more reliable on certain sites. Costs up to 5 credits per request. - **auto**: Firecrawl will automatically retry scraping with enhanced proxies if the basic proxy fails. If the retry with enhanced is successful, 5 credits will be billed for the scrape. If the first attempt with basic is successful, only the regular cost will be billed.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_proxy? Proxy { get; set; }
        /// <summary>Redact personally identifiable information from returned markdown. Pass `true` to use defaults, or an object to tune mode, entities, and replacement style.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII? RedactPII { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII RedactPII { get; set; }
#endif
        /// <summary>Removes all base 64 images from the markdown output, which may be overwhelmingly long. This does not affect html or rawHtml formats. The image&apos;s alt text remains in the output, but the URL is replaced with a placeholder.</summary>
        public bool? RemoveBase64Images { get; set; }
        /// <summary>Skip TLS certificate verification when making requests.</summary>
        public bool? SkipTlsVerification { get; set; }
        /// <summary>If true, the page will be stored in the Firecrawl index and cache. Setting this to false is useful if your scraping activity may have data protection concerns. Using some parameters associated with sensitive scraping (e.g. actions, headers) will force this parameter to be false.</summary>
        public bool? StoreInCache { get; set; }
        /// <summary>Per-request [Threat Protection](https://docs.firecrawl.dev/features/threat-protection) override. Fields you provide replace the corresponding fields of your organization&apos;s policy for this request only; omitted fields keep their organization-level values. Requires Threat Protection to be enabled for your team (enterprise feature) — otherwise the request is rejected with a 403. If your organization has disabled request overrides, any request that includes this object is rejected with a 403. If Threat Protection is enforced for your team, `mode` may not be set to `off`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ThreatProtectionOverride? ThreatProtection { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ThreatProtectionOverride ThreatProtection { get; set; }
#endif
        /// <summary>Timeout in milliseconds for the request. Minimum is 1000 (1 second). Default is 60000 (60 seconds). Maximum is 300000 (300 seconds).</summary>
        public int? Timeout { get; set; }
        /// <summary>Specify a delay in milliseconds before fetching the content, allowing the page sufficient time to load. This waiting time is in addition to Firecrawl&apos;s smart wait feature.</summary>
        public int? WaitFor { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions"/> and sets the default values.
        /// </summary>
        public ScrapeOptions()
        {
            AdditionalData = new Dictionary<string, object>();
            BlockAds = true;
            Lockdown = false;
            MaxAge = 172800000;
            Mobile = false;
            OnlyCleanContent = false;
            OnlyMainContent = true;
            Proxy = global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_proxy.Auto;
            RemoveBase64Images = true;
            SkipTlsVerification = true;
            StoreInCache = true;
            Timeout = 60000;
            WaitFor = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "blockAds", n => { BlockAds = n.GetBoolValue(); } },
                { "excludeTags", n => { ExcludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "formats", n => { Formats = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor.CreateFromDiscriminatorValue)?.AsList(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_headers>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_headers.CreateFromDiscriminatorValue); } },
                { "includeTags", n => { IncludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_location>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_location.CreateFromDiscriminatorValue); } },
                { "lockdown", n => { Lockdown = n.GetBoolValue(); } },
                { "maxAge", n => { MaxAge = n.GetIntValue(); } },
                { "minAge", n => { MinAge = n.GetIntValue(); } },
                { "mobile", n => { Mobile = n.GetBoolValue(); } },
                { "onlyCleanContent", n => { OnlyCleanContent = n.GetBoolValue(); } },
                { "onlyMainContent", n => { OnlyMainContent = n.GetBoolValue(); } },
                { "parsers", n => { Parsers = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_parsers>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_parsers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profile", n => { Profile = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_profile>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_profile.CreateFromDiscriminatorValue); } },
                { "proxy", n => { Proxy = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_proxy>(); } },
                { "redactPII", n => { RedactPII = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII.CreateFromDiscriminatorValue); } },
                { "removeBase64Images", n => { RemoveBase64Images = n.GetBoolValue(); } },
                { "skipTlsVerification", n => { SkipTlsVerification = n.GetBoolValue(); } },
                { "storeInCache", n => { StoreInCache = n.GetBoolValue(); } },
                { "threatProtection", n => { ThreatProtection = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ThreatProtectionOverride>(global::Soenneker.Firecrawl.OpenApiClient.Models.ThreatProtectionOverride.CreateFromDiscriminatorValue); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "waitFor", n => { WaitFor = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("actions", Actions);
            writer.WriteBoolValue("blockAds", BlockAds);
            writer.WriteCollectionOfPrimitiveValues<string>("excludeTags", ExcludeTags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor>("formats", Formats);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_headers>("headers", Headers);
            writer.WriteCollectionOfPrimitiveValues<string>("includeTags", IncludeTags);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_location>("location", Location);
            writer.WriteBoolValue("lockdown", Lockdown);
            writer.WriteIntValue("maxAge", MaxAge);
            writer.WriteIntValue("minAge", MinAge);
            writer.WriteBoolValue("mobile", Mobile);
            writer.WriteBoolValue("onlyCleanContent", OnlyCleanContent);
            writer.WriteBoolValue("onlyMainContent", OnlyMainContent);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_parsers>("parsers", Parsers);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_profile>("profile", Profile);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions_proxy>("proxy", Proxy);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII>("redactPII", RedactPII);
            writer.WriteBoolValue("removeBase64Images", RemoveBase64Images);
            writer.WriteBoolValue("skipTlsVerification", SkipTlsVerification);
            writer.WriteBoolValue("storeInCache", StoreInCache);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ThreatProtectionOverride>("threatProtection", ThreatProtection);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteIntValue("waitFor", WaitFor);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember1"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember10"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember11"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember12"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember13"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember14"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember15"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember16"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember2"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember3"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember4"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember5"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember6"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember7"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember8"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Monitor : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember1? MonitorMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember1 MonitorMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember10? MonitorMember10 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember10 MonitorMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember11? MonitorMember11 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember11 MonitorMember11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember12"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember12? MonitorMember12 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember12 MonitorMember12 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember13"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember13? MonitorMember13 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember13 MonitorMember13 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember14"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember14? MonitorMember14 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember14 MonitorMember14 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember15"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember15? MonitorMember15 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember15 MonitorMember15 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember16"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember16? MonitorMember16 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember16 MonitorMember16 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember2? MonitorMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember2 MonitorMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember3? MonitorMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember3 MonitorMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember4? MonitorMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember4 MonitorMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember5? MonitorMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember5 MonitorMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember6? MonitorMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember6 MonitorMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember7? MonitorMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember7 MonitorMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember8? MonitorMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember8 MonitorMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember9? MonitorMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember9 MonitorMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.Monitor();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MonitorMember1 != null)
                {
                    return MonitorMember1.GetFieldDeserializers();
                }
                else if(MonitorMember10 != null)
                {
                    return MonitorMember10.GetFieldDeserializers();
                }
                else if(MonitorMember11 != null)
                {
                    return MonitorMember11.GetFieldDeserializers();
                }
                else if(MonitorMember12 != null)
                {
                    return MonitorMember12.GetFieldDeserializers();
                }
                else if(MonitorMember13 != null)
                {
                    return MonitorMember13.GetFieldDeserializers();
                }
                else if(MonitorMember14 != null)
                {
                    return MonitorMember14.GetFieldDeserializers();
                }
                else if(MonitorMember15 != null)
                {
                    return MonitorMember15.GetFieldDeserializers();
                }
                else if(MonitorMember16 != null)
                {
                    return MonitorMember16.GetFieldDeserializers();
                }
                else if(MonitorMember2 != null)
                {
                    return MonitorMember2.GetFieldDeserializers();
                }
                else if(MonitorMember3 != null)
                {
                    return MonitorMember3.GetFieldDeserializers();
                }
                else if(MonitorMember4 != null)
                {
                    return MonitorMember4.GetFieldDeserializers();
                }
                else if(MonitorMember5 != null)
                {
                    return MonitorMember5.GetFieldDeserializers();
                }
                else if(MonitorMember6 != null)
                {
                    return MonitorMember6.GetFieldDeserializers();
                }
                else if(MonitorMember7 != null)
                {
                    return MonitorMember7.GetFieldDeserializers();
                }
                else if(MonitorMember8 != null)
                {
                    return MonitorMember8.GetFieldDeserializers();
                }
                else if(MonitorMember9 != null)
                {
                    return MonitorMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(MonitorMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember1>(null, MonitorMember1);
                }
                else if(MonitorMember10 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember10>(null, MonitorMember10);
                }
                else if(MonitorMember11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember11>(null, MonitorMember11);
                }
                else if(MonitorMember12 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember12>(null, MonitorMember12);
                }
                else if(MonitorMember13 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember13>(null, MonitorMember13);
                }
                else if(MonitorMember14 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember14>(null, MonitorMember14);
                }
                else if(MonitorMember15 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember15>(null, MonitorMember15);
                }
                else if(MonitorMember16 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember16>(null, MonitorMember16);
                }
                else if(MonitorMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember2>(null, MonitorMember2);
                }
                else if(MonitorMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember3>(null, MonitorMember3);
                }
                else if(MonitorMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember4>(null, MonitorMember4);
                }
                else if(MonitorMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember5>(null, MonitorMember5);
                }
                else if(MonitorMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember6>(null, MonitorMember6);
                }
                else if(MonitorMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember7>(null, MonitorMember7);
                }
                else if(MonitorMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember8>(null, MonitorMember8);
                }
                else if(MonitorMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.MonitorMember9>(null, MonitorMember9);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScrapeOptions_redactPII : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions? RedactPIIOptions { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions RedactPIIOptions { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.ScrapeOptions_redactPII();
                if("RedactPIIOptions".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RedactPIIOptions = new global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions();
                }
                else if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RedactPIIOptions != null)
                {
                    return RedactPIIOptions.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RedactPIIOptions != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.RedactPIIOptions>(null, RedactPIIOptions);
                }
                else if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
            }
        }
    }
}
#pragma warning restore CS0618
