// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>The result of the comparison between the two page versions. &apos;new&apos; means this page did not exist before, &apos;same&apos; means content has not changed, &apos;changed&apos; means content has changed, &apos;removed&apos; means the page was removed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ScrapeResponse_data_changeTracking_changeStatus
    {
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "same")]
        #pragma warning disable CS1591
        Same,
        #pragma warning restore CS1591
        [EnumMember(Value = "changed")]
        #pragma warning disable CS1591
        Changed,
        #pragma warning restore CS1591
        [EnumMember(Value = "removed")]
        #pragma warning disable CS1591
        Removed,
        #pragma warning restore CS1591
    }
}
