// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Brand colors extracted from the page.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScrapeResponse_data_branding_colors : IAdditionalDataHolder, IParsable
    {
        /// <summary>Accent color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Accent { get; set; }
#nullable restore
#else
        public string Accent { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Background color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Background { get; set; }
#nullable restore
#else
        public string Background { get; set; }
#endif
        /// <summary>Error/danger color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Link color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Link { get; set; }
#nullable restore
#else
        public string Link { get; set; }
#endif
        /// <summary>Primary brand color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Primary { get; set; }
#nullable restore
#else
        public string Primary { get; set; }
#endif
        /// <summary>Secondary brand color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Secondary { get; set; }
#nullable restore
#else
        public string Secondary { get; set; }
#endif
        /// <summary>Success/positive color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Success { get; set; }
#nullable restore
#else
        public string Success { get; set; }
#endif
        /// <summary>Primary text color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextPrimary { get; set; }
#nullable restore
#else
        public string TextPrimary { get; set; }
#endif
        /// <summary>Secondary text color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextSecondary { get; set; }
#nullable restore
#else
        public string TextSecondary { get; set; }
#endif
        /// <summary>Warning color (hex).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Warning { get; set; }
#nullable restore
#else
        public string Warning { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_branding_colors"/> and sets the default values.
        /// </summary>
        public ScrapeResponse_data_branding_colors()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_branding_colors"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_branding_colors CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_branding_colors();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accent", n => { Accent = n.GetStringValue(); } },
                { "background", n => { Background = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "link", n => { Link = n.GetStringValue(); } },
                { "primary", n => { Primary = n.GetStringValue(); } },
                { "secondary", n => { Secondary = n.GetStringValue(); } },
                { "success", n => { Success = n.GetStringValue(); } },
                { "textPrimary", n => { TextPrimary = n.GetStringValue(); } },
                { "textSecondary", n => { TextSecondary = n.GetStringValue(); } },
                { "warning", n => { Warning = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accent", Accent);
            writer.WriteStringValue("background", Background);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("link", Link);
            writer.WriteStringValue("primary", Primary);
            writer.WriteStringValue("secondary", Secondary);
            writer.WriteStringValue("success", Success);
            writer.WriteStringValue("textPrimary", TextPrimary);
            writer.WriteStringValue("textSecondary", TextSecondary);
            writer.WriteStringValue("warning", Warning);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
