// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>
    /// Results of the actions specified in the `actions` parameter. Only present if the `actions` parameter was provided in the request
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScrapeResponse_data_actions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>JavaScript return values, in the same order as the executeJavascript actions provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_javascriptReturns>? JavascriptReturns { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_javascriptReturns> JavascriptReturns { get; set; }
#endif
        /// <summary>PDFs generated, in the same order as the pdf actions provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Pdfs { get; set; }
#nullable restore
#else
        public List<string> Pdfs { get; set; }
#endif
        /// <summary>Scrape contents, in the same order as the scrape actions provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_scrapes>? Scrapes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_scrapes> Scrapes { get; set; }
#endif
        /// <summary>Screenshot URLs, in the same order as the screenshot actions provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Screenshots { get; set; }
#nullable restore
#else
        public List<string> Screenshots { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions"/> and sets the default values.
        /// </summary>
        public ScrapeResponse_data_actions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "javascriptReturns", n => { JavascriptReturns = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_javascriptReturns>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_javascriptReturns.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pdfs", n => { Pdfs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "scrapes", n => { Scrapes = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_scrapes>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_scrapes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "screenshots", n => { Screenshots = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_javascriptReturns>("javascriptReturns", JavascriptReturns);
            writer.WriteCollectionOfPrimitiveValues<string>("pdfs", Pdfs);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeResponse_data_actions_scrapes>("scrapes", Scrapes);
            writer.WriteCollectionOfPrimitiveValues<string>("screenshots", Screenshots);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
