// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SearchFeedbackRequest_rating
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "good")]
        #pragma warning disable CS1591
        Good,
        #pragma warning restore CS1591
        [EnumMember(Value = "bad")]
        #pragma warning disable CS1591
        Bad,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
    }
}
