// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Models
{
    /// <summary>URL scanning mode for this request. `normal` checks URLs against Google Web Risk (+2 credits per URL scanned).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ThreatProtectionOverride_mode
    {
        [EnumMember(Value = "off")]
        #pragma warning disable CS1591
        Off,
        #pragma warning restore CS1591
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
    }
}
