// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \search\{jobId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithJobItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The feedback property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder Feedback
        {
            get => new global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.WithJobItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJobItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/{jobId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.WithJobItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJobItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/{jobId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
