// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Firecrawl.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback
{
    /// <summary>
    /// Builds and executes requests for operations under \search\{jobId}\feedback
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FeedbackRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedbackRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/{jobId}/feedback", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeedbackRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/{jobId}/feedback", rawUrl)
        {
        }
        /// <summary>
        /// Submit feedback for a search job
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackResponse"/></returns>
        /// <param name="body">Substantive feedback is required by rating: good requires valuableSources; partial requires valuableSources or missingContent; bad requires missingContent or querySuggestions.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackResponse?> PostAsync(global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackResponse> PostAsync(global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse401Error.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse402Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse404Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse429Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.SearchFeedbackResponse500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackResponse>(requestInfo, global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Submit feedback for a search job
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Substantive feedback is required by rating: good requires valuableSources; partial requires valuableSources or missingContent; bad requires missingContent or querySuggestions.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Firecrawl.OpenApiClient.Models.SearchFeedbackRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Firecrawl.OpenApiClient.Search.Item.Feedback.FeedbackRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
