// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent.Item
{
    /// <summary>Model preset used for the agent run</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithJobGetResponse_model
    {
        [EnumMember(Value = "spark-1-pro")]
        #pragma warning disable CS1591
        Spark1Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "spark-1-mini")]
        #pragma warning disable CS1591
        Spark1Mini,
        #pragma warning restore CS1591
    }
}
