// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent.Item
{
    /// <summary>Why a failed run stopped early. `credit_limit_reached` means the run hit its `maxCredits` limit. Only present when status is failed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithJobGetResponse_stopReason
    {
        [EnumMember(Value = "credit_limit_reached")]
        #pragma warning disable CS1591
        Credit_limit_reached,
        #pragma warning restore CS1591
    }
}
