// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Crawl.ParamsPreview
{
    /// <summary>Sitemap handling strategy</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParamsPreviewPostResponse_data_sitemap
    {
        [EnumMember(Value = "skip")]
        #pragma warning disable CS1591
        Skip,
        #pragma warning restore CS1591
        [EnumMember(Value = "include")]
        #pragma warning disable CS1591
        Include,
        #pragma warning restore CS1591
    }
}
