// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search.Developer
{
    /// <summary>Set to `only` to limit the search to indexed agent-skill files.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeveloperPostRequestBody_skills
    {
        [EnumMember(Value = "only")]
        #pragma warning disable CS1591
        Only,
        #pragma warning restore CS1591
    }
}
