// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Firecrawl.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search.Developer
{
    /// <summary>
    /// Builds and executes requests for operations under \search\developer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeveloperRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeveloperRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/developer{?archived*,fork*,k*,language*,license*,max_stars*,min_stars*,passages*,repos*,skills*,sources*,topic*,types*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeveloperRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/developer{?archived*,fork*,k*,language*,license*,max_stars*,min_stars*,passages*,repos*,skills*,sources*,topic*,types*}", rawUrl)
        {
        }
        /// <summary>
        /// Search the developer index
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder.DeveloperRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder.DeveloperRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse>(requestInfo, global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search the developer index
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse?> PostAsync(global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse> PostAsync(global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse>(requestInfo, global::Soenneker.Firecrawl.OpenApiClient.Models.DeveloperSearchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search the developer index
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder.DeveloperRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder.DeveloperRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/search/developer?query={query}{&archived*,fork*,k*,language*,license*,max_stars*,min_stars*,passages*,repos*,skills*,sources*,topic*,types*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Search the developer index
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.DeveloperRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search the developer index
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeveloperRequestBuilderGetQueryParameters 
        {
            /// <summary>Include or exclude archived repositories. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
            [QueryParameter("archived")]
            public bool? Archived { get; set; }
            /// <summary>Include or exclude forks. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
            [QueryParameter("fork")]
            public bool? Fork { get; set; }
            /// <summary>Number of ranked results to return.</summary>
            [QueryParameter("k")]
            public int? K { get; set; }
            /// <summary>Repository primary language, such as `Rust`. Applies to repository results only; sending it with no `sources` scope returns no `doc` results. See [how the repository filters scope a search](/api-reference/endpoint/developer-search#how-the-repository-filters-scope-a-search).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
            /// <summary>Repository license, such as `MIT`. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("license")]
            public string? License { get; set; }
#nullable restore
#else
            [QueryParameter("license")]
            public string License { get; set; }
#endif
            /// <summary>Upper bound on repository stars. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
            [QueryParameter("max_stars")]
            public int? MaxStars { get; set; }
            /// <summary>Lower bound on repository stars. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
            [QueryParameter("min_stars")]
            public int? MinStars { get; set; }
            /// <summary>Matched passages to return per result.</summary>
            [QueryParameter("passages")]
            public int? Passages { get; set; }
            /// <summary>Natural-language question or search phrase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("query")]
            public string? Query { get; set; }
#nullable restore
#else
            [QueryParameter("query")]
            public string Query { get; set; }
#endif
            /// <summary>Repository slugs to scope the repository half of the index to, such as `firecrawl/firecrawl`. Applies to the `issue`, `pull_request`, and `readme` types only. Sent together with `sources`, the two halves are combined rather than intersected, so matching results come back from either. Returns 400 when no repository type is in `types`, reporting that `repos` cannot match any requested type and that you should add repository types or drop `repos`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("repos")]
            public string[]? Repos { get; set; }
#nullable restore
#else
            [QueryParameter("repos")]
            public string[] Repos { get; set; }
#endif
            /// <summary>Set to `only` to limit the search to indexed agent-skill files.</summary>
            [QueryParameter("skills")]
            public global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.GetSkillsQueryParameterType? Skills { get; set; }
            /// <summary>Documentation source ids to scope the documentation half to, at most 20. Applies to the `doc` type only. Not a fixed enum: ids reflect the documentation sites in the index and the set grows over time, so confirm an id resolves by sending it and reading the `sources` array on the response. Returns 400 with `sources cannot match any requested type; add doc or drop sources` when `doc` is not in `types`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sources")]
            public string[]? Sources { get; set; }
#nullable restore
#else
            [QueryParameter("sources")]
            public string[] Sources { get; set; }
#endif
            /// <summary>Repository topic, such as `async`. Applies to repository results only; sending it with no `sources` scope returns no `doc` results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("topic")]
            public string? Topic { get; set; }
#nullable restore
#else
            [QueryParameter("topic")]
            public string Topic { get; set; }
#endif
            /// <summary>Result kinds to search. Defaults to all four. Accepts a repeated parameter (`types=issue&amp;types=pull_request`) or one comma-separated value (`types=issue,pull_request`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("types")]
            public global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.GetTypesQueryParameterType[]? Types { get; set; }
#nullable restore
#else
            [QueryParameter("types")]
            public global::Soenneker.Firecrawl.OpenApiClient.Search.Developer.GetTypesQueryParameterType[] Types { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
