// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Firecrawl.OpenApiClient.Search.Research.Github;
using Soenneker.Firecrawl.OpenApiClient.Search.Research.Papers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Search.Research
{
    /// <summary>
    /// Builds and executes requests for operations under \search\research
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResearchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The github property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Search.Research.Github.GithubRequestBuilder Github
        {
            get => new global::Soenneker.Firecrawl.OpenApiClient.Search.Research.Github.GithubRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The papers property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Search.Research.Papers.PapersRequestBuilder Papers
        {
            get => new global::Soenneker.Firecrawl.OpenApiClient.Search.Research.Papers.PapersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Research.ResearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/research", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Search.Research.ResearchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/search/research", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
