// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent
{
    /// <summary>The model to use for the agent task. spark-1-mini (default) is 60% cheaper, spark-1-pro offers higher accuracy for complex tasks</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentPostRequestBody_model
    {
        [EnumMember(Value = "spark-1-mini")]
        #pragma warning disable CS1591
        Spark1Mini,
        #pragma warning restore CS1591
        [EnumMember(Value = "spark-1-pro")]
        #pragma warning disable CS1591
        Spark1Pro,
        #pragma warning restore CS1591
    }
}
