// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent
{
    /// <summary>`extract` returns the complete structured result in `data` every turn. `chat` lets a follow-up that asks for no new data get a short reply in `message` instead of a re-run. `exchange.requireApproval` needs `chat` on the same request. Omitted on a follow-up turn keeps the thread&apos;s mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AgentPostRequestBody_mode
    {
        [EnumMember(Value = "extract")]
        #pragma warning disable CS1591
        Extract,
        #pragma warning restore CS1591
        [EnumMember(Value = "chat")]
        #pragma warning disable CS1591
        Chat,
        #pragma warning restore CS1591
    }
}
