// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentGetResponse_agents : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>Integration identifier, if the run was started with one</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Integration { get; set; }
#nullable restore
#else
        public string Integration { get; set; }
#endif
        /// <summary>Options the run was started with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_options? Options { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_options Options { get; set; }
#endif
        /// <summary>Origin of the run (e.g. &quot;api&quot;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Origin { get; set; }
#nullable restore
#else
        public string Origin { get; set; }
#endif
        /// <summary>The settings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_settings? Settings { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_settings Settings { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_status? Status { get; set; }
        /// <summary>Short hint describing the run&apos;s target (first URL or prompt)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetHint { get; set; }
#nullable restore
#else
        public string TargetHint { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents"/> and sets the default values.
        /// </summary>
        public AgentGetResponse_agents()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "integration", n => { Integration = n.GetStringValue(); } },
                { "options", n => { Options = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_options>(global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_options.CreateFromDiscriminatorValue); } },
                { "origin", n => { Origin = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_settings>(global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_settings.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_status>(); } },
                { "targetHint", n => { TargetHint = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("integration", Integration);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_options>("options", Options);
            writer.WriteStringValue("origin", Origin);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_settings>("settings", Settings);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentGetResponse_agents_status>("status", Status);
            writer.WriteStringValue("targetHint", TargetHint);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
