// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Agent
{
    /// <summary>
    /// Answer yes to the `pendingApproval` the previous turn of this thread ended on. Needs `threadId`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AgentPostRequestBody_exchange_approve : IParsable
    {
        /// <summary>Stop asking for approval for the rest of the thread. Ignored on a `terms` approval.</summary>
        public bool? Always { get; set; }
        /// <summary>The `pendingApproval.id` to answer.</summary>
        public Guid? ApprovalId { get; set; }
        /// <summary>Run only these calls from the approval. Defaults to all of them. Ignored on a `terms` approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CallIds { get; set; }
#nullable restore
#else
        public List<string> CallIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentPostRequestBody_exchange_approve"/> and sets the default values.
        /// </summary>
        public AgentPostRequestBody_exchange_approve()
        {
            Always = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentPostRequestBody_exchange_approve"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentPostRequestBody_exchange_approve CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Agent.AgentPostRequestBody_exchange_approve();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "always", n => { Always = n.GetBoolValue(); } },
                { "approvalId", n => { ApprovalId = n.GetGuidValue(); } },
                { "callIds", n => { CallIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("always", Always);
            writer.WriteGuidValue("approvalId", ApprovalId);
            writer.WriteCollectionOfPrimitiveValues<string>("callIds", CallIds);
        }
    }
}
#pragma warning restore CS0618
