// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Firecrawl.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Scrape
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScrapePostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Actions to perform on the page before grabbing the content</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Actions { get; set; }
#nullable restore
#else
        public UntypedNode Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enables ad-blocking and cookie popup blocking.</summary>
        public bool? BlockAds { get; set; }
        /// <summary>Tags to exclude from the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludeTags { get; set; }
#nullable restore
#else
        public List<string> ExcludeTags { get; set; }
#endif
        /// <summary>Output formats to include in the response. You can specify one or more formats, either as strings (e.g., `&apos;markdown&apos;`) or as objects with additional options (e.g., `{ type: &apos;json&apos;, schema: {...} }`). Some formats require specific options to be set. Example: `[&apos;markdown&apos;, { type: &apos;json&apos;, schema: {...} }]`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape>? Formats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape> Formats { get; set; }
#endif
        /// <summary>Headers to send with the request. Can be used to send cookies, user-agent, etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_headers Headers { get; set; }
#endif
        /// <summary>Tags to include in the output.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludeTags { get; set; }
#nullable restore
#else
        public List<string> IncludeTags { get; set; }
#endif
        /// <summary>Location settings for the request. When specified, this will use an appropriate proxy if available and emulate the corresponding language and timezone settings. Defaults to &apos;US&apos; if not specified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_location? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_location Location { get; set; }
#endif
        /// <summary>Returns a cached version of the page if it is younger than this age in milliseconds. If a cached version of the page is older than this value, the page will be scraped. If you do not need extremely fresh data, enabling this can speed up your scrapes by 500%. Defaults to 2 days.</summary>
        public int? MaxAge { get; set; }
        /// <summary>When set, the request only checks the cache and never triggers a fresh scrape. The value is in milliseconds and specifies the minimum age the cached data must be. If matching cached data exists, it is returned instantly. If no cached data is found, a 404 with error code SCRAPE_NO_CACHED_DATA is returned. Set to 1 to accept any cached data regardless of age.</summary>
        public int? MinAge { get; set; }
        /// <summary>Set to true if you want to emulate scraping from a mobile device. Useful for testing responsive pages and taking mobile screenshots.</summary>
        public bool? Mobile { get; set; }
        /// <summary>Only return the main content of the page excluding headers, navs, footers, etc.</summary>
        public bool? OnlyMainContent { get; set; }
        /// <summary>Controls how files are processed during scraping. When &quot;pdf&quot; is included (default), the PDF content is extracted and converted to markdown format, with billing based on the number of pages (1 credit per page). When an empty array is passed, the PDF file is returned in base64 encoding with a flat rate of 1 credit for the entire PDF.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_parsers>? Parsers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_parsers> Parsers { get; set; }
#endif
        /// <summary>Enable persistent browser storage across scrape and interact sessions. Pass a profile when scraping to preserve cookies, localStorage, and session data. Sessions with the same profile name share browser state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_profile? Profile { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_profile Profile { get; set; }
#endif
        /// <summary>Specifies the type of proxy to use. - **basic**: Proxies for scraping sites with none to basic anti-bot solutions. Fast and usually works. - **enhanced**: Enhanced proxies for scraping sites with advanced anti-bot solutions. Slower, but more reliable on certain sites. Costs up to 5 credits per request. - **auto**: Firecrawl will automatically retry scraping with enhanced proxies if the basic proxy fails. If the retry with enhanced is successful, 5 credits will be billed for the scrape. If the first attempt with basic is successful, only the regular cost will be billed.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_proxy? Proxy { get; set; }
        /// <summary>Removes all base 64 images from the markdown output, which may be overwhelmingly long. This does not affect html or rawHtml formats. The image&apos;s alt text remains in the output, but the URL is replaced with a placeholder.</summary>
        public bool? RemoveBase64Images { get; set; }
        /// <summary>Skip TLS certificate verification when making requests.</summary>
        public bool? SkipTlsVerification { get; set; }
        /// <summary>If true, the page will be stored in the Firecrawl index and cache. Setting this to false is useful if your scraping activity may have data protection concerns. Using some parameters associated with sensitive scraping (e.g. actions, headers) will force this parameter to be false.</summary>
        public bool? StoreInCache { get; set; }
        /// <summary>Timeout in milliseconds for the request. Minimum is 1000 (1 second). Default is 60000 (60 seconds). Maximum is 300000 (300 seconds).</summary>
        public int? Timeout { get; set; }
        /// <summary>The URL to scrape</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Specify a delay in milliseconds before fetching the content, allowing the page sufficient time to load. This waiting time is in addition to Firecrawl&apos;s smart wait feature.</summary>
        public int? WaitFor { get; set; }
        /// <summary>If true, this will enable zero data retention for this scrape. To enable this feature, please contact help@firecrawl.dev</summary>
        public bool? ZeroDataRetention { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody"/> and sets the default values.
        /// </summary>
        public ScrapePostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Proxy = global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_proxy.Auto;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "blockAds", n => { BlockAds = n.GetBoolValue(); } },
                { "excludeTags", n => { ExcludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "formats", n => { Formats = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape>(global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape.CreateFromDiscriminatorValue)?.AsList(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_headers>(global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_headers.CreateFromDiscriminatorValue); } },
                { "includeTags", n => { IncludeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_location>(global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_location.CreateFromDiscriminatorValue); } },
                { "maxAge", n => { MaxAge = n.GetIntValue(); } },
                { "minAge", n => { MinAge = n.GetIntValue(); } },
                { "mobile", n => { Mobile = n.GetBoolValue(); } },
                { "onlyMainContent", n => { OnlyMainContent = n.GetBoolValue(); } },
                { "parsers", n => { Parsers = n.GetCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_parsers>(global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_parsers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profile", n => { Profile = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_profile>(global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_profile.CreateFromDiscriminatorValue); } },
                { "proxy", n => { Proxy = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_proxy>(); } },
                { "removeBase64Images", n => { RemoveBase64Images = n.GetBoolValue(); } },
                { "skipTlsVerification", n => { SkipTlsVerification = n.GetBoolValue(); } },
                { "storeInCache", n => { StoreInCache = n.GetBoolValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "waitFor", n => { WaitFor = n.GetIntValue(); } },
                { "zeroDataRetention", n => { ZeroDataRetention = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("actions", Actions);
            writer.WriteBoolValue("blockAds", BlockAds);
            writer.WriteCollectionOfPrimitiveValues<string>("excludeTags", ExcludeTags);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape>("formats", Formats);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_headers>("headers", Headers);
            writer.WriteCollectionOfPrimitiveValues<string>("includeTags", IncludeTags);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_location>("location", Location);
            writer.WriteIntValue("maxAge", MaxAge);
            writer.WriteIntValue("minAge", MinAge);
            writer.WriteBoolValue("mobile", Mobile);
            writer.WriteBoolValue("onlyMainContent", OnlyMainContent);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_parsers>("parsers", Parsers);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_profile>("profile", Profile);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody_proxy>("proxy", Proxy);
            writer.WriteBoolValue("removeBase64Images", RemoveBase64Images);
            writer.WriteBoolValue("skipTlsVerification", SkipTlsVerification);
            writer.WriteBoolValue("storeInCache", StoreInCache);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("waitFor", WaitFor);
            writer.WriteBoolValue("zeroDataRetention", ZeroDataRetention);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8"/>, <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Scrape : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1? ScrapeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1 ScrapeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10? ScrapeMember10 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10 ScrapeMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11? ScrapeMember11 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11 ScrapeMember11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2? ScrapeMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2 ScrapeMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3? ScrapeMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3 ScrapeMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4? ScrapeMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4 ScrapeMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5? ScrapeMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5 ScrapeMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6? ScrapeMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6 ScrapeMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7? ScrapeMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7 ScrapeMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8? ScrapeMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8 ScrapeMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9? ScrapeMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9 ScrapeMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Firecrawl.OpenApiClient.Scrape.ScrapePostRequestBody.Scrape();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember1 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember10 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember11 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember2 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember3 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember4 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember5 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember6 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember7 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember8 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ScrapeMember9 = new global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ScrapeMember1 != null)
                {
                    return ScrapeMember1.GetFieldDeserializers();
                }
                else if(ScrapeMember10 != null)
                {
                    return ScrapeMember10.GetFieldDeserializers();
                }
                else if(ScrapeMember11 != null)
                {
                    return ScrapeMember11.GetFieldDeserializers();
                }
                else if(ScrapeMember2 != null)
                {
                    return ScrapeMember2.GetFieldDeserializers();
                }
                else if(ScrapeMember3 != null)
                {
                    return ScrapeMember3.GetFieldDeserializers();
                }
                else if(ScrapeMember4 != null)
                {
                    return ScrapeMember4.GetFieldDeserializers();
                }
                else if(ScrapeMember5 != null)
                {
                    return ScrapeMember5.GetFieldDeserializers();
                }
                else if(ScrapeMember6 != null)
                {
                    return ScrapeMember6.GetFieldDeserializers();
                }
                else if(ScrapeMember7 != null)
                {
                    return ScrapeMember7.GetFieldDeserializers();
                }
                else if(ScrapeMember8 != null)
                {
                    return ScrapeMember8.GetFieldDeserializers();
                }
                else if(ScrapeMember9 != null)
                {
                    return ScrapeMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ScrapeMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember1>(null, ScrapeMember1);
                }
                else if(ScrapeMember10 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember10>(null, ScrapeMember10);
                }
                else if(ScrapeMember11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember11>(null, ScrapeMember11);
                }
                else if(ScrapeMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember2>(null, ScrapeMember2);
                }
                else if(ScrapeMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember3>(null, ScrapeMember3);
                }
                else if(ScrapeMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember4>(null, ScrapeMember4);
                }
                else if(ScrapeMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember5>(null, ScrapeMember5);
                }
                else if(ScrapeMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember6>(null, ScrapeMember6);
                }
                else if(ScrapeMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember7>(null, ScrapeMember7);
                }
                else if(ScrapeMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember8>(null, ScrapeMember8);
                }
                else if(ScrapeMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeMember9>(null, ScrapeMember9);
                }
            }
        }
    }
}
#pragma warning restore CS0618
