// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Firecrawl.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Extract
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExtractPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When true, the extraction will use web search to find additional data</summary>
        public bool? EnableWebSearch { get; set; }
        /// <summary>If invalid URLs are specified in the urls array, they will be ignored. Instead of them failing the entire request, an extract using the remaining valid URLs will be performed, and the invalid URLs will be returned in the invalidURLs field of the response.</summary>
        public bool? IgnoreInvalidURLs { get; set; }
        /// <summary>When true, sitemap.xml files will be ignored during website scanning</summary>
        public bool? IgnoreSitemap { get; set; }
        /// <summary>When true, subdomains of the provided URLs will also be scanned</summary>
        public bool? IncludeSubdomains { get; set; }
        /// <summary>Prompt to guide the extraction process</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>Schema to define the structure of the extracted data. Must conform to [JSON Schema](https://json-schema.org/).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody_schema? Schema { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody_schema Schema { get; set; }
#endif
        /// <summary>The scrapeOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions? ScrapeOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions ScrapeOptions { get; set; }
#endif
        /// <summary>When true, the sources used to extract the data will be included in the response as `sources` key</summary>
        public bool? ShowSources { get; set; }
        /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Urls { get; set; }
#nullable restore
#else
        public List<string> Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody"/> and sets the default values.
        /// </summary>
        public ExtractPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enableWebSearch", n => { EnableWebSearch = n.GetBoolValue(); } },
                { "ignoreInvalidURLs", n => { IgnoreInvalidURLs = n.GetBoolValue(); } },
                { "ignoreSitemap", n => { IgnoreSitemap = n.GetBoolValue(); } },
                { "includeSubdomains", n => { IncludeSubdomains = n.GetBoolValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "schema", n => { Schema = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody_schema>(global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody_schema.CreateFromDiscriminatorValue); } },
                { "scrapeOptions", n => { ScrapeOptions = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.CreateFromDiscriminatorValue); } },
                { "showSources", n => { ShowSources = n.GetBoolValue(); } },
                { "urls", n => { Urls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enableWebSearch", EnableWebSearch);
            writer.WriteBoolValue("ignoreInvalidURLs", IgnoreInvalidURLs);
            writer.WriteBoolValue("ignoreSitemap", IgnoreSitemap);
            writer.WriteBoolValue("includeSubdomains", IncludeSubdomains);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Extract.ExtractPostRequestBody_schema>("schema", Schema);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions>("scrapeOptions", ScrapeOptions);
            writer.WriteBoolValue("showSources", ShowSources);
            writer.WriteCollectionOfPrimitiveValues<string>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
