// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Firecrawl.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Crawl
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CrawlPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Allows the crawler to follow links to external websites.</summary>
        public bool? AllowExternalLinks { get; set; }
        /// <summary>Allows the crawler to follow links to subdomains of the main domain.</summary>
        public bool? AllowSubdomains { get; set; }
        /// <summary>Allows the crawler to follow internal links to sibling or parent URLs, not just child paths.false: Only crawls deeper (child) URLs.→ e.g. /features/feature-1 → /features/feature-1/tips ✅→ Won&apos;t follow /pricing or / ❌true: Crawls any internal links, including siblings and parents.→ e.g. /features/feature-1 → /pricing, /, etc. ✅Use true for broader internal coverage beyond nested paths.</summary>
        public bool? CrawlEntireDomain { get; set; }
        /// <summary>Delay in seconds between scrapes. This helps respect website rate limits. Setting this forces concurrency to 1.</summary>
        public double? Delay { get; set; }
        /// <summary>URL pathname regex patterns that exclude matching URLs from the crawl. For example, if you set &quot;excludePaths&quot;: [&quot;blog/.*&quot;] for the base URL firecrawl.dev, any results matching that pattern will be excluded, such as https://www.firecrawl.dev/blog/firecrawl-launch-week-1-recap.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludePaths { get; set; }
#nullable restore
#else
        public List<string> ExcludePaths { get; set; }
#endif
        /// <summary>Do not re-scrape the same path with different (or none) query parameters</summary>
        public bool? IgnoreQueryParameters { get; set; }
        /// <summary>Ignore the website&apos;s robots.txt rules. Enterprise only — contact support@firecrawl.com to enable.</summary>
        public bool? IgnoreRobotsTxt { get; set; }
        /// <summary>URL pathname regex patterns that include matching URLs in the crawl. Only the paths that match the specified patterns will be included in the response. Note: the starting URL is also checked against these patterns — if it does not match, the crawl may return 0 pages. For example, if you set &quot;includePaths&quot;: [&quot;blog/.*&quot;] for the base URL firecrawl.dev/blog, only pages under /blog/ will be included in the results, such as https://www.firecrawl.dev/blog/firecrawl-launch-week-1-recap.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IncludePaths { get; set; }
#nullable restore
#else
        public List<string> IncludePaths { get; set; }
#endif
        /// <summary>Maximum number of pages to crawl. Default limit is 10000.</summary>
        public int? Limit { get; set; }
        /// <summary>Maximum number of concurrent scrapes. This parameter allows you to set a concurrency limit for this crawl. If not specified, the crawl adheres to your team&apos;s concurrency limit.</summary>
        public int? MaxConcurrency { get; set; }
        /// <summary>Maximum depth to crawl based on discovery order. The root site and sitemapped pages has a discovery depth of 0. For example, if you set it to 1, and you set `sitemap: &apos;skip&apos;`, you will only crawl the entered URL and all URLs that are linked on that page.</summary>
        public int? MaxDiscoveryDepth { get; set; }
        /// <summary>A prompt to use to generate the crawler options (all the parameters below) from natural language. Explicitly set parameters will override the generated equivalents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prompt { get; set; }
#nullable restore
#else
        public string Prompt { get; set; }
#endif
        /// <summary>When true, includePaths and excludePaths regex patterns are matched against the full URL (including query parameters) instead of just the URL pathname. Useful when you need to filter URLs based on query strings.</summary>
        public bool? RegexOnFullURL { get; set; }
        /// <summary>Custom User-Agent string for robots.txt evaluation. When set, robots.txt is fetched with this User-Agent and allow/disallow rules are matched against it instead of the default. Enterprise only — contact support@firecrawl.com to enable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RobotsUserAgent { get; set; }
#nullable restore
#else
        public string RobotsUserAgent { get; set; }
#endif
        /// <summary>The scrapeOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions? ScrapeOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions ScrapeOptions { get; set; }
#endif
        /// <summary>Sitemap mode when crawling. If you set it to &apos;skip&apos;, the crawler will ignore the website sitemap and only crawl the entered URL and discover pages from there onwards. If you set it to &apos;only&apos;, the crawler will only crawl URLs from the sitemap (plus the start URL) and will not discover links from HTML.</summary>
        public global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_sitemap? Sitemap { get; set; }
        /// <summary>The base URL to start crawling from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>A webhook specification object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_webhook? Webhook { get; set; }
#nullable restore
#else
        public global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_webhook Webhook { get; set; }
#endif
        /// <summary>If true, this will enable zero data retention for this crawl. To enable this feature, please contact help@firecrawl.dev</summary>
        public bool? ZeroDataRetention { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody"/> and sets the default values.
        /// </summary>
        public CrawlPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Sitemap = global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_sitemap.Include;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowExternalLinks", n => { AllowExternalLinks = n.GetBoolValue(); } },
                { "allowSubdomains", n => { AllowSubdomains = n.GetBoolValue(); } },
                { "crawlEntireDomain", n => { CrawlEntireDomain = n.GetBoolValue(); } },
                { "delay", n => { Delay = n.GetDoubleValue(); } },
                { "excludePaths", n => { ExcludePaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ignoreQueryParameters", n => { IgnoreQueryParameters = n.GetBoolValue(); } },
                { "ignoreRobotsTxt", n => { IgnoreRobotsTxt = n.GetBoolValue(); } },
                { "includePaths", n => { IncludePaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "maxConcurrency", n => { MaxConcurrency = n.GetIntValue(); } },
                { "maxDiscoveryDepth", n => { MaxDiscoveryDepth = n.GetIntValue(); } },
                { "prompt", n => { Prompt = n.GetStringValue(); } },
                { "regexOnFullURL", n => { RegexOnFullURL = n.GetBoolValue(); } },
                { "robotsUserAgent", n => { RobotsUserAgent = n.GetStringValue(); } },
                { "scrapeOptions", n => { ScrapeOptions = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions>(global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions.CreateFromDiscriminatorValue); } },
                { "sitemap", n => { Sitemap = n.GetEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_sitemap>(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "webhook", n => { Webhook = n.GetObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_webhook>(global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_webhook.CreateFromDiscriminatorValue); } },
                { "zeroDataRetention", n => { ZeroDataRetention = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowExternalLinks", AllowExternalLinks);
            writer.WriteBoolValue("allowSubdomains", AllowSubdomains);
            writer.WriteBoolValue("crawlEntireDomain", CrawlEntireDomain);
            writer.WriteDoubleValue("delay", Delay);
            writer.WriteCollectionOfPrimitiveValues<string>("excludePaths", ExcludePaths);
            writer.WriteBoolValue("ignoreQueryParameters", IgnoreQueryParameters);
            writer.WriteBoolValue("ignoreRobotsTxt", IgnoreRobotsTxt);
            writer.WriteCollectionOfPrimitiveValues<string>("includePaths", IncludePaths);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("maxConcurrency", MaxConcurrency);
            writer.WriteIntValue("maxDiscoveryDepth", MaxDiscoveryDepth);
            writer.WriteStringValue("prompt", Prompt);
            writer.WriteBoolValue("regexOnFullURL", RegexOnFullURL);
            writer.WriteStringValue("robotsUserAgent", RobotsUserAgent);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Models.ScrapeOptions>("scrapeOptions", ScrapeOptions);
            writer.WriteEnumValue<global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_sitemap>("sitemap", Sitemap);
            writer.WriteStringValue("url", Url);
            writer.WriteObjectValue<global::Soenneker.Firecrawl.OpenApiClient.Crawl.CrawlPostRequestBody_webhook>("webhook", Webhook);
            writer.WriteBoolValue("zeroDataRetention", ZeroDataRetention);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
