// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Crawl
{
    /// <summary>Sitemap mode when crawling. If you set it to &apos;skip&apos;, the crawler will ignore the website sitemap and only crawl the entered URL and discover pages from there onwards. If you set it to &apos;only&apos;, the crawler will only crawl URLs from the sitemap (plus the start URL) and will not discover links from HTML.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CrawlPostRequestBody_sitemap
    {
        [EnumMember(Value = "skip")]
        #pragma warning disable CS1591
        Skip,
        #pragma warning restore CS1591
        [EnumMember(Value = "include")]
        #pragma warning disable CS1591
        Include,
        #pragma warning restore CS1591
        [EnumMember(Value = "only")]
        #pragma warning disable CS1591
        Only,
        #pragma warning restore CS1591
    }
}
