// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Browser
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BrowserPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>WebSocket URL for Chrome DevTools Protocol access</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CdpUrl { get; set; }
#nullable restore
#else
        public string CdpUrl { get; set; }
#endif
        /// <summary>When the session will expire based on TTL</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The unique session identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>URL to interact with the browser session in real time (click, type, scroll)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InteractiveLiveViewUrl { get; set; }
#nullable restore
#else
        public string InteractiveLiveViewUrl { get; set; }
#endif
        /// <summary>URL to view the browser session in real time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiveViewUrl { get; set; }
#nullable restore
#else
        public string LiveViewUrl { get; set; }
#endif
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Firecrawl.OpenApiClient.Browser.BrowserPostResponse"/> and sets the default values.
        /// </summary>
        public BrowserPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Firecrawl.OpenApiClient.Browser.BrowserPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Firecrawl.OpenApiClient.Browser.BrowserPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Firecrawl.OpenApiClient.Browser.BrowserPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cdpUrl", n => { CdpUrl = n.GetStringValue(); } },
                { "expiresAt", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "interactiveLiveViewUrl", n => { InteractiveLiveViewUrl = n.GetStringValue(); } },
                { "liveViewUrl", n => { LiveViewUrl = n.GetStringValue(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cdpUrl", CdpUrl);
            writer.WriteDateTimeOffsetValue("expiresAt", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("interactiveLiveViewUrl", InteractiveLiveViewUrl);
            writer.WriteStringValue("liveViewUrl", LiveViewUrl);
            writer.WriteBoolValue("success", Success);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
