// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Team.Activity
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEndpointQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "scrape")]
        #pragma warning disable CS1591
        Scrape,
        #pragma warning restore CS1591
        [EnumMember(Value = "crawl")]
        #pragma warning disable CS1591
        Crawl,
        #pragma warning restore CS1591
        [EnumMember(Value = "batch_scrape")]
        #pragma warning disable CS1591
        Batch_scrape,
        #pragma warning restore CS1591
        [EnumMember(Value = "search")]
        #pragma warning disable CS1591
        Search,
        #pragma warning restore CS1591
        [EnumMember(Value = "extract")]
        #pragma warning disable CS1591
        Extract,
        #pragma warning restore CS1591
        [EnumMember(Value = "llmstxt")]
        #pragma warning disable CS1591
        Llmstxt,
        #pragma warning restore CS1591
        [EnumMember(Value = "deep_research")]
        #pragma warning disable CS1591
        Deep_research,
        #pragma warning restore CS1591
        [EnumMember(Value = "map")]
        #pragma warning disable CS1591
        Map,
        #pragma warning restore CS1591
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
        [EnumMember(Value = "interact")]
        #pragma warning disable CS1591
        Interact,
        #pragma warning restore CS1591
    }
}
