// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Firecrawl.OpenApiClient.Monitor.Item.Checks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "skipped_overlap")]
        #pragma warning disable CS1591
        Skipped_overlap,
        #pragma warning restore CS1591
    }
}
